apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-db
  labels:
    app: grafana-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce # required
  storageClassName: local-storage
  local:
      path: /volumes/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-manager-1.copicus.ru